/**
 * Action type constants.
@author Ganesh Khutwad
 */
const actionTypes = {
    ADD_EMPLOYEE_SUCCESS: 'ADD_EMPLOYEE_SUCCESS',
    LOAD_EMPLOYEES_SUCCESS: 'LOAD_EMPLOYEES_SUCCESS',
    UPDATE_EMPLOYEE_SUCCESS: 'UPDATE_EMPLOYEE_SUCCESS',
    DELETE_EMPLOYEE_SUCCESS: 'DELETE_EMPLOYEE_SUCCESS',

    LOAD_USER_INFO_SUCCESS: 'LOAD_USER_INFO_SUCCESS',
    SET_ADD_OPERATION_SUCCESS: 'SET_ADD_OPERATION_SUCCESS',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',

    LOAD_FEEDBACK_QUESTIONS_SUCCESS: 'LOAD_FEEDBACK_QUESTIONS_SUCCESS',
    ADD_FEEDBACK_SUCCESS: 'ADD_FEEDBACK_SUCCESS',
    UNSET_FEEDBACK_ADDED_STATUS: 'UNSET_FEEDBACK_ADDED_STATUS'
};

export default actionTypes;
